- nodestream/databases/neo4j/query.py
> Fix typo in neo4j driver's query.py

- nodestream/pipeline/pipeline.py
We need to ignore flushes when outputting the stream of resultant records from neo4j.
> Ignore Flush operations in Pipeline#run()

- nodestream/databases/database_connector.py
- nodestream/databases/neo4j/__init__.py
- nodestream/databases/neo4j/database_connector.py
- nodestream/databases/neo4j/query_executor.py
- nodestream/databases/query_executor.py
- nodestream/databases/writer.py
- tests/unit/databases/neo4j/test_ingest_query_buiilder.py
- tests/unit/databases/neo4j/test_query_executor.py
Due to our future plans of having migrations and other deeper integrations with internals of the database, this PR introduces a `DatabaseConnector` class that represents the integration point between a database and nodestream. With features like the migrations and more advanced indexing support, we are likely going to need to grow the interface beyond what the `QueryExecutor` is designed to do. The new `DatabaseConnector` class can act as the top level interface a database implementation needs to implement.
In short, instead of the `GraphDatabaseWriter` creating a `QueryExecutor` directly, it creates a `DatabaseConnector` and asks the `DatabaseConnector` to create a `QueryExecutor`.
> Refactor: Introduce Database Connectors Concept

- docs/docs/reference/extractors.md
- nodestream/pipeline/extractors/apis.py
- tests/unit/pipeline/extractors/test_apis.py
Prior to the open-sourcing of this project, we had a mechanism for pulling JSON data from simple APIs. This adds that feature.
> Add `SimpleAPIExtractor` 

- docs/docs/guides/implementing-pipeline-testing.md
- nodestream/pipeline/pipeline_file_loader.py
- nodestream/project/pipeline_progress_reporter.py
- nodestream/project/project.py
- nodestream/project/run_request.py
- tests/unit/pipeline/test_pipeline_file_loader.py
- tests/unit/project/test_pipeline_progress_reporter.py
- tests/unit/project/test_project.py
Prior to this project being open sourced, we had/have a mechanism to snapshot the results of a pipeline's execution, and compare them against known good. This brings that support into `nodestream`.
> Add `Project#get_snapshot_for` API

- docs/docs/reference/value-providers.md
- nodestream/pipeline/value_providers/__init__.py
- nodestream/pipeline/value_providers/regex_value_provider.py
- tests/unit/pipeline/value_providers/test_regex_value_provider.py
Adds a Value provider that works be regex-ing another value provider. The docs provide more details on usage.
> Add `RegexValueProvider`

- nodestream/pipeline/argument_resolvers/include_file_resolver.py
> fix include_file method

- tests/unit/pipeline/argument_resolvers/conftest.py
- tests/unit/pipeline/argument_resolvers/fixtures/with_env.yaml
- tests/unit/pipeline/argument_resolvers/test_environment_variable_resolver.py
Add a pattern for testing argument resolvers. The pattern relies on creating a file loader that respects a provided argument resolver and loading a test file. Preconditions can be met in the test case. For instance, what this PR does to add a test value to the environment.
> Add `unit` test harness for argument resolvers

- docs/docs/reference/interpreter.md
- nodestream/interpreting/interpreter.py
- tests/unit/interpreting/test_interpreter.py
In the interpreter component, you can specify two different blocks of interpretations. `interpretations` and `before_iteration`. The `before_iteration` block is applied for a record is broken down into sub-records and applied to the `interpretations` block. 
Users can also specify `lists` of `lists` of  interpretations in the `interpretations` block. Because both the `interpreations` block and `before_iteration` block are parsed and loaded the same way, its possible to supply a list of lists to the `before_iteration` block.  However that is not respected in anyway. This provides a confusing experience to users that try and use this. 
To resolve this, this PR iterates over each sublist in `before_iteration` If provided, and performs the iteration and interpretation based on the output of …
> Respect the cardinality of `before_iteration` clauses in the interpreter

- nodestream/cli/commands/run.py
- nodestream/cli/operations/run_pipeline.py
- nodestream/pipeline/pipeline.py
- nodestream/pipeline/pipeline_file_loader.py
- tests/unit/cli/operations/test_run_pipeline.py
- tests/unit/pipeline/test_pipeline.py
- tests/unit/pipeline/test_pipeline_progress_reporter.py
The outbox size represents the upper-bound of how many items can be buffered from a step before the step is blocked from continuing.  This PR introduces an option to set this value for different performance environments.
> Add an option to bound outbox size

- nodestream/databases/neo4j/ingest_query_builder.py
- nodestream/databases/neo4j/query.py
- tests/unit/databases/neo4j/test_ingest_query_buiilder.py
We never ported the code that actually performs the TTL. This code includes the deletion operations.
> Actually execute TTL delete operations

- docs/docs/reference/extractors.md
- nodestream/pipeline/extractors/files.py
- tests/unit/pipeline/extractors/test_files.py
In the case where you have a series of files, each file should be loaded and yielded in a predictable order so that an appropriate snapshot is able to be created. If objects are continuously yielded in various orders, it means that one can not rely on the ordering. While, for most extractors, this isn't a big deal as you are not likely to snapshot them or the extractor has an obvious ordering. However in the case of the file extractor which takes a series of globs, its not obvious the ordering. This makes it so that is the case.
> Yield files in order in `FileExtractor`

- nodestream/project/pipeline_definition.py
- nodestream/project/project.py
- tests/unit/project/test_pipeline_definition.py
* fix config parsing parameter error when initializing pipeline
> add config in initialization

- nodestream/pipeline/extractors/files.py
- tests/unit/pipeline/extractors/test_files.py
Adds parsing support for `jsonl` files.
> Parse `jsonl` files

- nodestream/databases/neo4j/query.py
#87  introduced a bug in the commit query. This fixes it so the right parameters get passed now.  Since we have debouncing, `paralell: true` can also be set.
> Fix Broken Commit Query

- nodestream/cli/commands/run.py
- nodestream/cli/commands/shared_options.py
- nodestream/cli/operations/run_pipeline.py
- nodestream/pipeline/pipeline_file_loader.py
- nodestream/project/project.py
- tests/unit/cli/operations/test_run_pipeline.py
- tests/unit/project/test_project.py
- [When you do `-vv` on `nodestream run` the effective configuration is printed](https://github.com/nodestream-proj/nodestream/commit/d1dd28b61efcb7691471d6055fc532517cf06e59)
- [You can now pass multiple pipeline names to `nodestream run`](https://github.com/nodestream-proj/nodestream/commit/193df10bf1c2090ede6c1e6600456577439446d5)
- [If you pass no pipelines to `nodestream run`, all pipelines are run](https://github.com/nodestream-proj/nodestream/commit/193df10bf1c2090ede6c1e6600456577439446d5)
> Run Command Improvements

- nodestream/pipeline/extractors/streams/extractor.py
- nodestream/pipeline/extractors/streams/kafka.py
- tests/unit/pipeline/extractors/streams/test_extractor.py
- tests/unit/pipeline/extractors/streams/test_kafka.py
- The timeout and polling values are now provided to stream connectors instead of setting defaults for all extractors. This allows the ability to have multiple types of StreamConnectors with different polling and timeout settings.
> Move stream poll values into stream declaration

- docs/docs/tutorial.md
- nodestream/cli/commands/run.py
- nodestream/cli/operations/generate_pipeline_scaffold.py
- nodestream/cli/operations/run_pipeline.py
- nodestream/databases/__init__.py
- nodestream/pipeline/pipeline_file_loader.py
- nodestream/project/__init__.py
- nodestream/project/project.py
- nodestream/project/target.py
- tests/unit/cli/operations/test_run_pipeline.py
- tests/unit/project/fixtures/simple_project_with_targets.yaml
- tests/unit/project/test_project.py
- tests/unit/project/test_target.py
Implements the feature described in #138
> Implement Targets

- nodestream/model/desired_ingestion.py
- tests/unit/model/test_desired_ingestion.py
The call to `run_hook` in `IngestionStrategy` was not correctly made according to the signature. This fixes that and adds an appropriate test.
> Fix incorrect call to Ingest Strategy in Hooks

- docs/docs/guides/creating-your-own-argument-resolver.md
- docs/docs/guides/project-plugins.md
- nodestream/file_io.py
- nodestream/pipeline/argument_resolvers/argument_resolver.py
- nodestream/pipeline/argument_resolvers/environment_variable_resolver.py
- nodestream/pipeline/argument_resolvers/include_file_resolver.py
- nodestream/pipeline/scope_config.py
- nodestream/project/project.py
- nodestream/project/target.py
- tests/unit/project/test_project.py
- tests/unit/project/test_scope_config.py
- tests/unit/project/test_target.py
This PR introduces two related changes to improve the  approach taken to load the project file:
- It allows `ProjectPlugins` to implement a `before_project_loaded` and `after_project_loaded` hooks to better time changes to the project that the plugin may wish to make. 
- Introduce a delayed loading methodology that allows tags that are used for resolvers to be loaded after the fact for targets and scopes. This allows one to introspect the project without loading all required configuration.
> Redesign Project Load Behavior for Delayed Evaluation

- pyproject.toml
- scripts/rev-official-plugins.sh
This script revs the versions of `nodestream` in all the core packages and prepares them for release. This is a side step on the goal to document and automate the release process.
> Add a New Release Script for 0.10

- nodestream/model/graph_objects.py
- tests/unit/model/test_graph_objects.py
We need all parts of the key to be defined. If we cannot, then we cannot ingest the record.
> Fix: Handle Nulls for Multi-Key Relationships

- nodestream/databases/debounced_ingest_strategy.py
- nodestream/databases/writer.py
- nodestream/pipeline/writers.py
- tests/unit/databases/test_debounced_ingest_strategy.py
- tests/unit/databases/test_graph_database_writer.py
- tests/unit/pipeline/test_writers.py
This PR introduces two fixes in `Writer` Logic:
- `Writers` did not handle flush globally, but rather required it to be handled locally. This pulls additional handling to the `Writer` base class. 
- Hooks were re-executed between batches.
> Fix Ingest Hooks and Writers

- README.md
README license badge is showing GPL3, while the LICENSE in the repo is Apache 2.0. Updating the badge to reflect the license change.
> Update README license badge

- nodestream/pipeline/extractors/stores/aws/s3_extractor.py
Some pipelines have been failing because of the following error:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/nodestream/pipeline/extractors/stores/aws/s3_extractor.py", line 90, in extract_records
self.archive_s3_object(key)
File "/usr/local/lib/python3.11/site-packages/nodestream/pipeline/extractors/stores/aws/s3_extractor.py", line 51, in archive_s3_object
self.s3_client.copy_object(
File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 553, in _api_call
return self._make_api_call(operation_name, kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 1009, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An …
```
> Use Multi-Part Copy when Archiving S3 Objects from Processing

- nodestream/model/graph_objects.py
- tests/unit/model/test_graph_objects.py
Much of the code base assumes that nodes with no key parts are not possible (which is by design). However, the logic to invalidate nodes that do not have a key defined is not present. note: `all` on an empty iterable returns `True`. 
This closes #248
> Make nodes with No ID invalid

- nodestream/pipeline/extractors/files.py
- tests/unit/pipeline/extractors/stores/aws/test_s3_extractor.py
- Fix error when parsing jsonl documents from s3 extractor.
- iterator of `StringIO` type returns type `bytes`, using iterator of `StringIO.readlines()` returns type `str`
- File reader open as bytes and specify reader in file handlers
> fix jsonl line parsing

- nodestream/databases/neo4j/query.py
This was a typo from the query. This value is being ignored because of casing. 
The reason this value should can be set is that large transactions can cause major turmoil when it its updating with large transactions of relationships (Especially against large data sets). 
See here in the docs:
https://neo4j.com/docs/apoc/current/overview/apoc.periodic/apoc.periodic.iterate/
> Correct batchsize to be batchSize

- nodestream/cli/operations/run_project_cookiecutter.py
- tests/unit/cli/operations/test_run_project_cookiecutter.py
Compliments changes from this PR: 
https://github.com/nodestream-proj/nodestream-project-cookiecutter/pull/1
> Support Multiple Databases On `nodestream new` 

- docs/docs/reference/interpretations.md
- nodestream/interpreting/interpretations/properties_interpretation.py
- nodestream/interpreting/interpretations/property_mapping.py
- nodestream/interpreting/interpretations/relationship_interpretation.py
- nodestream/interpreting/interpretations/source_node_interpretation.py
- tests/integration/fixtures/pipelines/airports.yaml
- tests/unit/interpreting/interpretations/test_properties_iterpretation.py
- tests/unit/interpreting/interpretations/test_property_mapping.py
- tests/unit/interpreting/interpretations/test_relationship_interpretation.py
- tests/unit/interpreting/interpretations/test_source_node_interpretation.py
See the documentation in the Pull Request for more details. 
This allows you to dynamically bind properties by specifying a map directly instead of individual fields.
> Add Properties By Directly Specifying a Mapping Value

- nodestream/databases/neo4j/database_connector.py
- nodestream/databases/neo4j/ingest_query_builder.py
- nodestream/databases/neo4j/query.py
- nodestream/databases/neo4j/query_executor.py
- tests/unit/databases/neo4j/test_ingest_query_buiilder.py
- tests/unit/databases/neo4j/test_query_executor.py
Due to some internal analysis done by intuit, while this query does perform better is certain situations, in others it can cause memory consumption spikes in the 10s of GBs on the cluster and can cause stability and consistency issues. This PR approaches using the more obvious MERGE path and leaving it to the database to execute this more in a stable manor. This PR also adds several settings (currently undocumented) that allow for some tweaking of the underlying batch performance. 
NOTE: Docs excluded from this PR pending the docs revamp.
> Improve Neo4j Query Performance By Using MERGE

- nodestream/model/graph_objects.py
- tests/unit/model/test_graph_objects.py
This worked more by coincidence than by design. The key needs to be ordered by the pairs not just the values.
> Fix nodes with key properties of differing types crashing nodestream

- nodestream/pipeline/pipeline_file_loader.py
- nodestream/pipeline/step.py
- tests/unit/pipeline/test_pipeline_file.py
Due to a missing/ineffective test during the refactor, setting scope level config was not working.  This PR adds back setting scope level config and adds a test that ensures that set config is loaded from yaml correctly.
> Regression: Fix Issue with Scope Config Being Dropped

- nodestream/databases/neo4j/query_executor.py
- nodestream/pipeline/pipeline.py
- nodestream/pipeline/value_providers/normalizer_value_provider.py
- tests/integration/test_pipeline_error_propagation.py
- tests/unit/pipeline/value_providers/test_normalizer_value_provider.py
- Fixing a bug with the normalize value provider that crashes when the data returns None. 
- Adding database uri for logging. This can be used to specify logs between different database targets.
- Increase the timeout window for error collecting tests for more deterministic tests.
> Modified the normalizer to handle single values properly + Neo4j Writer Logs URI

- nodestream/interpreting/interpretations/interpretation.py
- nodestream/interpreting/interpretations/source_node_interpretation.py
- nodestream/interpreting/interpretations/switch_interpretation.py
- nodestream/schema/printers/graphql_schema_printer.py
- nodestream/schema/state.py
- tests/data/dns.csv
- tests/data/people.json
- tests/integration/fixtures/pipelines/dns.yaml
- tests/integration/fixtures/pipelines/people.yaml
- tests/integration/snapshots/schema_snapshot_airports.yaml_graphql.txt
- tests/integration/snapshots/schema_snapshot_dns.yaml_graphql.txt
- tests/integration/snapshots/schema_snapshot_dns.yaml_plain.txt
- tests/integration/snapshots/schema_snapshot_fifa_2021_player_data.yaml_graphql.txt
- tests/integration/snapshots/schema_snapshot_people.yaml_graphql.txt
- tests/integration/snapshots/schema_snapshot_people.yaml_plain.txt
- tests/integration/test_pipeline_and_data_interpretation.py
- tests/unit/schema/printers/test_graphql_schema_printer.py
There are two issues with schema introspection. Specifically: 
- If you have a switch statement that provides completely different set of interpretations per-branch, then it will merge the schemas together. This is in appropriate because each branch provides a different part of the schema that should be isolated and only merged together once complete. This PR prevents this from occurring. 
- If you attempt to define a relationship interpretation before defining the source node, it will not be bound to the source node type. 
- Fix a syntax issue in the graphql schema.
> Fix Edge Cases in Schema Introspection

- nodestream/databases/database_connector.py
- nodestream/databases/null.py
- nodestream/databases/writer.py
- nodestream/project/project.py
- nodestream/project/target.py
- nodestream/schema/state.py
- tests/unit/project/test_target.py
- tests/unit/schema/test_state.py
This PR Fixes two issues:
1. If you have two pipelines; one that says a property is a key and another that says it only knows the property as a property, the order of operations takes precedence. This occurs when using a match only clause. If we know something is a key, it needs to be defined as such. Same thing with indexes. 
2. Currently we are passing writer configurations (such as `batch_size`) through the target. Currently these values are getting passed as part of the the connector configuration directly to the writer that is able to sort through these arguments and use them. However, with the addition of the `Migrator`, these configuration values are treated as invalid. This PR shuffles the writer configuration values as well the connector specific values away from one another and …
> Fix `Target` and `Schema` bugs

- nodestream/cli/operations/run_pipeline.py
- nodestream/subclass_registry.py
- playground_project/nodestream.yaml
- tests/unit/cli/operations/test_run_pipeline.py
- tests/unit/test_subclass_registry.py
This adds two new error messages: 
- When there are no targets for the pipeline; provides a warning that it is running the pipeline without writing anywhere. 
- When you hit a `MissingFromRegistryError`, the message now asks you if you forgot to install a plugin.
> Add Slightly Better Error Messages

- nodestream/project/pipeline_definition.py
- tests/unit/project/test_pipeline_definition.py
In any pipeline configuration, inherit the paren't annotations then overwrite them with our annotations within the configuration's scope.
> Fixed the effective annotations from overwriting from parent

- nodestream/pipeline/value_providers/regex_value_provider.py
- tests/unit/pipeline/value_providers/test_regex_value_provider.py
Currently Regex Value Provider automatically anchors to the begging of the string. That means that searching the string for a specific pattern would always require having .* in the beginning.
Ex:
Given:
text = "I am Kevin"
1) regex = "Kevin" - Would find no matches
2) regex = ".*Kevin" - would find matches
Since this is not a common constraint on regexes, using python `re.search()` method will result in matches being found for both regexes.
> Search for matches anywhere in the string

- nodestream/schema/migrations/auto_change_detector.py
- nodestream/schema/migrations/migrator.py
- tests/unit/schema/migrations/test_auto_detector.py
- tests/unit/schema/migrations/test_migrator.py
This PR introduces two changes to migrations: 
1. Fixes an issue where properties that have been promoted to keys are considered dropped. 
2. Fixes an issue where the migration lock is not released after a failure. This means that in the cases where a spurious error occurs, the migrations cannot be reran without manually removing the lock.
> Fix Migrator Resiliency Issues

- .github/workflows/ci.yaml
Github has been putting out some warnings on the need to migrate to node 20 based actions. See [here](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).
> Bump to Node 20 Based Actions

- .github/workflows/release.yaml
- pyproject.toml
This PR uses short-lived OIDC tokens to publish built packages to PyPi. Additionally, it uses Github's Attestations features to produce an attestation on the provenance of packages so developers can verify it is untampered.
> Automatically Release with OIDC and Attestations

- docs/docs/reference/extractors.md
- docs/docs/reference/file-formats.md
- nodestream/pipeline/extractors/files.py
- nodestream/pipeline/extractors/stores/aws/s3_extractor.py
- nodestream/subclass_registry.py
- tests/unit/pipeline/extractors/stores/aws/test_s3_extractor.py
- tests/unit/pipeline/extractors/test_files.py
Add support for .gz and .bz2 compressed files in `SupportedFileFormat`.
> add gzip and bz2 compressed file format support

- nodestream/interpreting/interpretations/relationship_interpretation.py
- nodestream/schema/state.py
- tests/unit/interpreting/interpretations/matchers.py
- tests/unit/interpreting/interpretations/test_relationship_interpretation.py
- tests/unit/schema/test_state.py
This change allows the developer to do the following:
Modify the cardinality of a relationship from the declaration of the interpretation
Override the cardinality of a relationship from the override schema. 
It also outputs the cardinalities of the schema when creating an output of the schema.
> Cardinality Overrides

- nodestream/pipeline/extractors/credential_utils.py
- poetry.lock
- pyproject.toml
- tests/unit/pipeline/extractors/stores/aws/test_credential_utils.py
By default, if we do not assume a role, we grab a basic boto score session which gets the credentials without refreshing. This PR introduces a change to fall back on a regular boto3 session which will fetch again from the provider chain.
> AWS Credentials Refresh when Not Assuming Roles

- nodestream/pipeline/extractors/credential_utils.py
- pyproject.toml
We were accidentlly supplying args intended for boto3 to botocore. In this case, we do not need to supply those args at all, we just need to get the credentials.
> Minor Fix to Local Credential Logic

- nodestream/interpreting/interpretation_passes.py
- nodestream/pipeline/extractors/files.py
- nodestream/pipeline/extractors/stores/aws/s3_extractor.py
- tests/unit/pipeline/extractors/stores/aws/test_s3_extractor.py
- tests/unit/pipeline/extractors/test_files.py
In this PR, we a complete refactoring to the internals of the file handling logic that allows for increased interoperability and maintainability between file handling logic and sources. To accomplish this, the PR introduces the following changes: 
- Rename `SupportedFileFormat` and `SupportedCompressedFileFormat` to `FileCodec` and `CompressionCodec` respectively to provide a better naming for their changed roles. Now, these types simply provided the decode behaviors and do not own a file in anyway.
- Introduce `ReadableFile` and its subclasses which define methods for building reader types from `self` as well as defining the `path` of the file (which can be a non-real path).
- Introduce `FileSource` and its subclasses which essentially work to build instances of `ReadableFile` and return …
> Refactor File Handling Code to Fix S3 Incompatability Issues

- nodestream/interpreting/interpretations/source_node_interpretation.py
- tests/integration/snapshots/interpretation_snapshot_fifa_2021_player_data.yaml.json
- tests/unit/interpreting/interpretations/test_source_node_interpretation.py
> Fix `do_lowercase_strings` being applied to everything in `SourceNodeInterpretation`

- nodestream/cli/commands/__init__.py
- nodestream/cli/commands/squash_migrations.py
- nodestream/cli/operations/__init__.py
- nodestream/cli/operations/generate_squashed_migration.py
- nodestream/schema/migrations/migrations.py
- nodestream/schema/migrations/operations.py
- nodestream/schema/migrations/project_migrations.py
- nodestream/schema/migrations/state_providers.py
- tests/unit/cli/commands/test_squash_migrations.py
- tests/unit/cli/operations/test_generate_squashed_migration.py
- tests/unit/schema/migrations/test_migrations.py
- tests/unit/schema/migrations/test_operations.py
- tests/unit/schema/migrations/test_project_migrations.py
This feature adds a new `nodestream migrations squash --from x --to y` command. `x` and `y` would be the names of migrations that you want to squash between. If y is left off, then the last migration is specified. 
Closes #299
> Squash Migrations

- nodestream/pipeline/normalizers/normalizer.py
- nodestream/pipeline/value_providers/normalizer_value_provider.py
- tests/unit/pipeline/normalizers/test_lowercase_strings.py
- tests/unit/pipeline/normalizers/test_remove_trailing_dots.py
- tests/unit/pipeline/normalizers/test_trim_whitespace.py
Often times `Normalizer` classes need to have a straight `None` check to prevent any issues during normalization. Almost all normalizers would do this. This change makes it so that the default behavior is to reject none values unless the class opts into normalizing the value.
> Reject none values by default in Normalizers

- nodestream/pipeline/extractors/stores/aws/dynamodb_extractor.py
- tests/unit/pipeline/extractors/stores/aws/test_dynamo_extractor.py
Using boto3 deserializer method to unmarshall the dynamo records rather than our own version. In order to use the best standards for type standardization.
> Unmarshalling dynamo data officially.

- nodestream/pipeline/value_providers/__init__.py
- nodestream/pipeline/value_providers/cast_value_provider.py
- tests/unit/pipeline/value_providers/test_cast_value_provider.py
Provides a mechanism for basic data manipulation by casting the provided value to a basic data type.
```
!cast 
value: !jmespath some.value.here
to: int
```
> Add Cast Value Provider

- nodestream/metrics.py
Provides a small fix to the way we're rendering statistics in table form to be better readable.
> Fix Metric Report for Table Output

- nodestream/pipeline/extractors/stores/aws/dynamodb_extractor.py
- tests/unit/pipeline/extractors/stores/aws/test_dynamo_extractor.py
Cleans up the implementation of DynamoDB to use boto3 for pagination handling.
> Simply DynamoDB Pagination Using Boto3

- nodestream/pipeline/object_storage.py
- tests/unit/pipeline/test_object_storage.py
This is the first in a series of PRs intended to address #301. NOTE: Target branch is `0.14` - not `main`.
This PR (on its own) introduces only dead code into the library. As described in the issue description, in order to have extractor checkpoints we need to describe storage apis for the contents of those checkpoints. This PR introduces that core behavior and APIs including:
- Namespacing (which will be used to different checkpoints for different pipelines and versions of that pipeline. 
- Signature Verification - to prevent tampering of those checkpoints
- Object storage itself
> Implement Object Storage APIs

- nodestream/cli/operations/run_copy.py
- nodestream/cli/operations/run_pipeline.py
- nodestream/pipeline/extractors/extractor.py
- nodestream/pipeline/extractors/iterable.py
- nodestream/pipeline/object_storage.py
- nodestream/pipeline/pipeline.py
- nodestream/pipeline/pipeline_file_loader.py
- nodestream/pipeline/step.py
- tests/integration/test_pipeline_flush_handling.py
- tests/unit/pipeline/extractors/test_iterable_extractor.py
- tests/unit/pipeline/test_object_storage.py
- tests/unit/pipeline/test_pipeline_progress_reporter.py
- tests/unit/pipeline/test_step.py
- tests/unit/test_extractor.py
**Note this is stacked on top of [saga/checkpoints/object-store-apis](https://github.com/nodestream-proj/nodestream/tree/saga/checkpoints/object-store-apis)**
This logic wires object storage through the pipeline and into a testing extractor workload. This proves out the workflow and is working. Follow up PRs can include supporting this for more extractors.
> Working Basic Checkpointing

- nodestream/interpreting/interpretations/__init__.py
- nodestream/interpreting/interpretations/conditions.py
- nodestream/interpreting/interpretations/interpretation.py
- tests/unit/interpreting/interpretations/test_interpretation.py
- tests/unit/interpreting/test_conditions.py
Prior to migration to OSS, we had a `only_when` field that allowed a comparator between two providers to trigger the actual evaluation. This is reintroducing and turbo-charging that feature.
> Condition Interpretations
