nodestream-proj/nodestream

nodestream/pluggable.py
Fix `is_plugin` class plugin evaluation
=> fix is_plugin plugin class evaluation

docs_overrides/main.html, mkdocs.yml, poetry.lock, pyproject.toml, scripts/release.sh
- Adds a release script to formalize the release process
- Adds versioning to the docs so that you can refer to previous versions.
=> Add Better Versioning

tests/unit/pipeline/argument_resolvers/fixtures/with_file.yaml, tests/unit/pipeline/argument_resolvers/fixtures/with_file_include.yaml, tests/unit/pipeline/argument_resolvers/test_include_file_resolver.py
- Test include_file argument resolver
=> test file resolvers

docs/technology.md
Add a document explaining `asyncio`
=> Add a document explaining `asyncio`

docs/docs/reference/extractors.md, nodestream/databases/neo4j/extractor.py, tests/unit/databases/neo4j/test_extractor.py
Prior to this being open sourced, we had this component. This pulls that component into the OSS code base.
=> Add a Neo4j Extractor 

docs/docs/guides/ingestion-hooks.md
=> Document Ingestion Hooks

nodestream/pipeline/extractors/stores/aws/athena_extractor.py
=> fix athena extractor data conversion

pyproject.toml
Fix references in pyproject.toml
=> update pyproject references

nodestream/pipeline/extractors/streams/kafka.py
Add ability to pass mandatory `ssl_context` option when selecting `SSL` security_protocol
=> add option for ssl_context

nodestream/pipeline/extractors/streams/extractor.py, nodestream/pipeline/extractors/streams/kafka.py, tests/unit/pipeline/extractors/streams/test_kafka.py
Fix async error in stream extractor
=> fix async errors

nodestream/pipeline/extractors/streams/extractor.py
Add error logging for extractor poll message exceptions
=> add logging for extractor poll message exceptions

nodestream/pipeline/extractors/__init__.py
=> export simple api extractor

nodestream/pipeline/extractors/streams/kafka.py
=> fix string join

nodestream/pipeline/extractors/streams/extractor.py, nodestream/pipeline/extractors/streams/kafka.py
Refactor logic in extractor and kafka connector
=> cleanup stream extractor and kafka connector logic

nodestream/pipeline/__init__.py, nodestream/pipeline/filters.py, tests/unit/pipeline/test_filters.py
Add the ability to filter a record based on a regex (include/exclude)
=> Add regex filter

nodestream/file_io.py, nodestream/project/project.py, nodestream/project/target.py, tests/unit/project/test_project.py
=> Don't Destroy Users Project When Using `nodestream scaffold` and `nodestream remove`

docs/docs/reference/value-providers.md, nodestream/pipeline/normalizers/normalizer.py, nodestream/pipeline/value_providers/__init__.py, nodestream/pipeline/value_providers/normalizer_value_provider.py, nodestream/subclass_registry.py, tests/unit/pipeline/value_providers/test_normalizer_value_provider.py
The documentation in the PR explains the use case. Incidentally this makes some strides in improving the issue specified in #148 as well.
=> Add a Normalize Value Provider

nodestream/pipeline/argument_resolvers/include_file_resolver.py, nodestream/project/pipeline_definition.py, nodestream/project/pipeline_scope.py, nodestream/project/plugin.py, tests/unit/pipeline/argument_resolvers/fixtures/with_file.yaml, tests/unit/pipeline/argument_resolvers/test_include_file_resolver.py, tests/unit/project/fixtures/simple_project_with_config_targets.yaml, tests/unit/project/test_pipeline_definition.py, tests/unit/project/test_project.py
BUGFIX
- Resolve tags inside !include tag files
- Add in the reading of declared targets from scope level in the project file
=> fix resolving tags inside import resolver files

nodestream/project/pipeline_definition.py, nodestream/project/pipeline_scope.py, tests/unit/project/fixtures/simple_project_with_config_targets.yaml, tests/unit/project/test_pipeline_definition.py, tests/unit/project/test_project.py
- Add pipeline option for disabling inherited targets
=> add option for disabling scope targets

nodestream/pipeline/transformers/transformer.py, tests/unit/pipeline/transformers/test_transformer.py
The default case was not optional and the PassTransformer was not being initialized properly.
=> Switch transformer fix

docs/docs/reference/file-formats.md, nodestream/pipeline/extractors/files.py, tests/unit/pipeline/extractors/test_files.py
Adds `.yaml` data file handling.
=> Add Yaml File Format

nodestream/pipeline/transformers/expand_json_field.py, tests/unit/pipeline/transformers/test_expand_json_field.py
- Handles null values in path parts 
- Handles invalid (for the object) paths.
=> Handle null values and broken paths in ExpandJsonField

nodestream/project/plugin.py, nodestream/project/project.py, tests/unit/project/test_plugin.py, tests/unit/project/test_project.py
- Load plugin configurations and plugin scope add.
=> fix loading plugin config

nodestream/pipeline/pipeline.py, tests/integration/test_pipeline_error_propagation.py
DoneObject was not being propagated.
=> Fixed the propagation of the DoneObject upon pipeline failure

pyproject.toml
Create pre-release for sqs extractor
=> pre-release

nodestream/pipeline/extractors/files.py, nodestream/pipeline/extractors/queues/sqs.py, tests/unit/pipeline/extractors/queues/test_sqs.py
=> fix message deletion

nodestream/pipeline/extractors/files.py, nodestream/pipeline/extractors/stores/aws/s3_extractor.py, tests/unit/pipeline/extractors/stores/aws/test_s3_extractor.py
Update SupportedFileFormat to take extension override, update S3 extractor to use extension override when provided
=> Fix S3 Extractor object_format

nodestream/pipeline/extractors/files.py, pyproject.toml
This was missing the pluggable entry point to allow external packages.
=> Actually file format support

nodestream/cli/commands/run_migrations.py, tests/unit/cli/commands/test_run_migrations.py
=> Add All Targets Flag to `nodestream migrations run`

nodestream/pipeline/extractors/files.py, nodestream/pipeline/extractors/stores/aws/s3_extractor.py, tests/unit/pipeline/extractors/test_files.py
This implements the design as discussed in #339
=> Add declarative interface to `UnifiedFileExtractor`

nodestream/databases/debounced_ingest_strategy.py
See the comment in the source code for explanation.
=> Adjust Ingest Strategy to Prevent Relationship Deadlocks

nodestream/pipeline/object_storage.py, tests/unit/pipeline/test_object_storage.py
Adds an S3 Object Storage Implementation and equivalent tests.
=> S3 Object Storage

.gitignore, Makefile
A few very small changes to the project for convince sake.
=> Spring Cleaning

nodestream/pipeline/extractors/ttls.py
Implementing the Checkpoint API for TTL extractor.
=> TTL Checkpointing

poetry.lock, pyproject.toml
Forgot to rev the version. From the file, it looks like 0.14.1 had the same problem?
=> chore: upgrade version number

nodestream/schema/printers/graphql_schema_printer.py, nodestream/schema/state.py
Describes list types and then renders them in the GQL renderer.
=> Add Mappings for Descrbing List Types
